### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by rbran** [rbran/HelpPet-uvv#1]
Descrito no Edital: Os produtos acima elencados deverão ser apresentados em 01 (um) banner no tamanho A0 da ABNT 118,9 cm de largura por 84,1cm de altura) com canaletas para sustentação. 

Colocar o arquivo do banner em multimidia/

Não precisa fazer todo de uma vez, pode ir fazendo por partes e ir dando **commits**, lembrem de deixar um comentário com o commit abaixo.

**Comment by AnaBeatriz1234** [comment]
Banner

**Comment by JosefButzke** [comment]
Banner

**Comment by rbran** [comment]
Não precisa escrever Banner, você pode deixar o comentário do que vocês fizeram exatamente:
Exemplo:
* Introdução
* Plano de fundo

**Comment by JosefButzke** [comment]
Impressão do banner

**Comment by rbran** [comment]
É boa pratica deixar comentado o commit que foi feito. Mas como vocês são noob eu mesmo faço: 80ee119

**Comment by AnaBeatriz1234** [comment]
Fiz a introdução
