### ISSUE TITLE
Logomarca

### ISSUE THREAD

**Issue by rbran** [rbran/HelpPet-uvv#17]
É Preciso uma logomarca para ser utilizada no site e no banner, algo que possa se tornar a imagem do projeto.

**Comment by bittti** [comment]
Ok, vou pensar em algo, e ver com a equipe de Design.

**Comment by Xula** [comment]
Estou participando da criação do banner, logotipo e outrs artes que serão desenvolvidas!

**Comment by FlavianeRibeiro** [comment]
Participação na criação do banner e Logotipo

**Comment by rbran** [comment]
![logo1](https://raw.githubusercontent.com/rbran/HelpPet-uvv/master/multimidia/logo1.jpg)

**Comment by rbran** [comment]
![logo2](https://raw.githubusercontent.com/rbran/HelpPet-uvv/master/multimidia/logo2.jpg)

**Comment by rbran** [comment]
Deem um "Like" nos que vcs acharam melhor

**Comment by ThaynaValadares** [comment]
Participação na criação do banner e Logotipo..

**Comment by rbran** [comment]
Ok, a logo 2 ganhou! 
@ju-carvalh0,@Xula, @FlavianeRibeiro e @bittti , façam upload da logo2 original e atualizem a jpg pra que ela fique sem essa "grade" no fundo. Assim que vocês fizerem, comentem aqui q eu fecho essa tarefa.

**Comment by ju-carvalh0** [comment]
Ok, vou conversar com eles e atualizamos lá.

________________________________
De: rbran <notifications@github.com>
Enviado: quinta-feira, 14 de abril de 2016 20:21:44
Para: rbran/HelpPet-uvv
Cc: Ju Carvalho
Assunto: Re: [rbran/HelpPet-uvv] Logomarca (#17)


Ok, a logo 2 ganhou!
@ju-carvalh0<https://github.com/ju-carvalh0>,@Xula<https://github.com/Xula>, @FlavianeRibeiro<https://github.com/FlavianeRibeiro> e @bittti<https://github.com/bittti> , façam upload da logo2 original e atualizem a jpg pra que ela fique sem essa "grade" no fundo. Assim que vocês fizerem, comentem aqui q eu fecho essa tarefa.

-

**Comment by FlavianeRibeiro** [comment]
Ok :)

**Comment by Xula** [comment]
![logo-helpet](https://cloud.githubusercontent.com/assets/17917067/14583190/89608be0-03f0-11e6-88cd-2091bc195337.png)

**Comment by rbran** [comment]
Faz upload do arquivo original tmb (se possível em svg)

**Comment by laisbaptista** [comment]
Participação na criação do banner

**Comment by AnaBeatriz1234** [comment]
criação do banner e design do site

**Comment by JosefButzke** [comment]
Eu vou cuidar do banner.
