### ISSUE TITLE
Projeto do banco de dados

### ISSUE THREAD

**Issue by rbran** [rbran/HelpPet-uvv#2]
Precisa fazer.

- [x]  Modelo entidade relacionamento
- [x]  Modelo no Mysql-Workbench
- [ ] Sql Final

**Comment by rbran** [comment]
Implementado o sistema básico do BD em dedd894240860657ab4788fa5ce7ceb4f46a58a1

**Comment by Erindor** [comment]
Onde está o modelo entidade relacionamente o MySql-Workbench?

**Comment by rbran** [comment]
Tá em "etc/banco-de-dados.mwb"

**Comment by rbran** [comment]
Foi feito o sql em faff88748b844a9c47170e05bb379247f1bf0b45 e corrigido os erros basicos em 439aa2b5ece221dd91f6f261ae4e47566b767517.
