### ISSUE TITLE
Bug ao abrir paginas Google Chrome /Windows 7

### ISSUE THREAD

**Issue by Xula** [rbran/HelpPet-uvv#42]
Depois de mudar varias vezes de pagina para fazer os testes percebi que  elas param de carregar e ficam em branco apos o loading, 

http://prntscr.com/b41cap
http://prntscr.com/b41cn5

**Comment by rbran** [comment]
erro com sua internet.

**Comment by rbran** [comment]
não era bug

**Comment by Xula** [comment]
bom fiz o teste varias vezes e continuou, mas então esta beleza.

**Comment by rbran** [comment]
Ctrl-R ou F5 Resolve.
